### ISSUE TITLE
typescript-mongodb-beginners-tutorial incorrect route parameters syntax

### ISSUE THREAD

**Issue by dv1x3r** [elliotforbes/tutorialedge.net#19]
Hello,
I was looking for examples of url parameter usage in express framework and have found an error with [typescript-mongodb-beginners-tutorial.md](https://github.com/elliotforbes/tutorialedge-v2/blob/master/content/typescript/typescript-mongodb-beginners-tutorial.md) tutorial:

``` javascript
// API Endpoints
app.get("/", book.allBooks);
app.get("/{id}", book.getBook);
app.post("/", book.addBook);
app.put("/{id}", book.updateBook);
app.delete("/{id}", book.deleteBook);
```

Curly braces does not work in my solution. According to the [official guide](https://expressjs.com/tr/guide/routing.html), curly braces should be replaced with colon like this

``` javascript
// API Endpoints
app.get("/", book.allBooks);
app.get("/:id", book.getBook);
app.post("/", book.addBook);
app.put("/:id", book.updateBook);
app.delete("/:id", book.deleteBook);
```

**Comment by elliotforbes** [comment]
This has been updated! Apologies for the delay in fixing this, I do seriously appreciate the help!
