### ISSUE TITLE
Search is Non-responsive

### ISSUE THREAD

**Issue by pocc** [elliotforbes/tutorialedge.net#82]
The search page loads, but hitting return does nothing.

Confirmed on

* Macos/Chrome
* Macos/Firefox
* Xubuntu/Firefox
* iOS/Chrome

**Comment by elliotforbes** [comment]
Should be fixed now, the site's performance has been improved by removing stuff that is no longer necessary and the search page has been redesigned as well!

Cheers for pointing this out and helping with the site once again!
