### ISSUE TITLE
You have many twins you weren't aware of

### ISSUE THREAD

**Issue by pocc** [elliotforbes/tutorialedge.net#88]
Unless you have a twin, Brian L. Troutwine should get a different photo.
<img width="968" alt="Screen Shot 2019-07-24 at 3 37 40 PM" src="https://user-images.githubusercontent.com/10995145/61833512-600f0500-ae29-11e9-80df-96ec7d7c02c7.png">

I am sure there are other examples of this.

**Comment by elliotforbes** [comment]
Sorted! The author image was set on that article for some strange reason!
